use super::safe_library::SafeLibrary;
use super::*;
use crate::errors::Result;
use crate::objects::Value;
use crate::props;
use crate::runtime_env::native_fns::NATIVE_TABLE;
use rustc_hash::FxHashMap;
use std::path::Path;
use std::rc::Rc;

use crate::well_known as wk;

impl Interpreter {
    fn load_native_library(&mut self, lib_path: &Path) -> Option<FxHashMap<String, Value>> {
        let library = SafeLibrary::new(lib_path).ok()?;
        let mut props = FxHashMap::default();

        type InitFn = fn() -> *mut tails_abi::ModuleHandle;

        // Try module-specific init first, then fallback to generic
        let module_stem = lib_path.file_stem().and_then(|s| s.to_str()).unwrap_or("");
        let base_name = module_stem.strip_prefix("lib").unwrap_or(module_stem);

        // Resolve init symbol; copy the typed fn pointer out of the Symbol
        // so we do not need to keep the Symbol alive for the call.
        //
        // # Safety
        // `get_function` requires that `InitFn` matches the exported symbol.
        // Init symbols are generated by `tails_module` / ABI macros.
        let init_fn: InitFn = unsafe {
            // Try several naming conventions to find the init function. The
            // `tails_native_init_*` macro emits a symbol that includes the
            // full module name (e.g. `tails_native_init_tails_process`), so
            // we also try prepending the `tails_` prefix.
            let candidates = [
                format!("tails_native_init_{}", base_name.replace('-', "_")),
                format!("tails_native_init_{}", base_name),
                format!("tails_native_init_tails_{}", base_name.replace('-', "_")),
                format!("tails_native_init_tails_{}", base_name),
                "tails_native_init".to_string(),
            ];
            let mut found = None;
            for name in &candidates {
                if let Ok(f) = library.get_function::<InitFn>(name) {
                    found = Some(*f);
                    break;
                }
            }
            found
        }?;

        let handle = init_fn();
        if handle.is_null() {
            return None;
        }
        // Safety: handle comes from tails_native_init and is checked for null.
        // Ownership transfers from the native module to this Box.
        let handle = unsafe { tails_abi::take_module_handle(handle) };

        for (func_name, func_ptr) in &handle.module.functions {
            // Store typed NativeFn — no transmute at call sites.
            let idx = self.dynamic_native_fns.len();
            self.dynamic_native_fns.push(*func_ptr);

            props.insert(
                func_name.clone(),
                Value::NativeFunction(NATIVE_TABLE.len() + idx),
            );
        }

        // Register class methods from DTS metadata
        let mut class_methods: HashMap<String, FxHashMap<String, Value>> = HashMap::new();
        for func_name in props.keys() {
            if let Some(method_name) = func_name.strip_prefix("counter_") {
                class_methods
                    .entry("Counter".to_string())
                    .or_default()
                    .insert(method_name.to_string(), props[func_name].clone());
            }
        }
        for (class_name, methods) in class_methods {
            self.native_class_registry.insert(class_name, methods);
        }

        // Safety: The library must remain loaded for the function pointers in props
        // to stay valid. Dropping SafeLibrary would unload the underlying Library,
        // invalidating every pointer we stored in `props`. Using `mem::forget`
        // intentionally skips the Drop impl so the native library stays in memory
        // for the lifetime of the process.
        std::mem::forget(library);

        Some(props)
    }

    pub fn execute_module(&mut self, module: &CompiledModule) -> Result<Value> {
        let saved_module = self.current_module.take();
        self.current_module = Some(Rc::new(module.clone()));
        let prev_exports = std::mem::take(&mut self.module_exports);
        let saved_globals = std::mem::take(&mut self.globals);
        // Node-compatible: every built-in global is visible inside modules.
        // (A narrow allow-list previously omitted TypedArrays, Error helpers, …)
        self.globals = saved_globals.clone();

        // Inject __filename, __dirname, module, exports globals
        if let Some(ref path) = self.current_module_path {
            self.globals
                .insert("__filename".to_string(), Value::from_string(path.clone()));
            let dir = std::path::Path::new(path)
                .parent()
                .map(|p| p.to_string_lossy().to_string())
                .unwrap_or_else(|| ".".to_string());
            self.globals
                .insert("__dirname".to_string(), Value::from_string(dir));

            // inject import.meta with url property (file:// URL)
            let file_url = if path.starts_with('/') {
                format!("file://{}", path)
            } else {
                format!(
                    "file://{}/{}",
                    std::env::current_dir()
                        .map(|d| d.to_string_lossy().to_string())
                        .unwrap_or_default(),
                    path
                )
            };
            let meta_props = props! {
                "url" => Value::from_string(file_url),
            };
            let meta_obj_idx = self.gc.allocate(
                &mut self.heap,
                HeapValue::Object(crate::vm::interpreter::JsObject {
                    properties: meta_props,
                    prototype: None,
                    extensible: true,
                }),
            );
            let import_props = props! {
                "meta" => Value::Object(meta_obj_idx),
            };
            let import_obj_idx = self.gc.allocate(
                &mut self.heap,
                HeapValue::Object(crate::vm::interpreter::JsObject {
                    properties: import_props,
                    prototype: None,
                    extensible: true,
                }),
            );
            self.globals
                .insert("import".to_string(), Value::Object(import_obj_idx));

            // Also inject module and exports for CJS compatibility
            let module_obj = self.new_object();
            let exports_obj = self.new_object();
            self.set_property_str(&module_obj, "exports", exports_obj.clone());
            self.globals.insert("module".to_string(), module_obj);
            self.globals.insert("exports".to_string(), exports_obj);
        }

        let module_globals_cell = std::rc::Rc::new(std::cell::RefCell::new(self.globals.clone()));
        let saved_mg = self.module_globals.clone();
        let saved_mg_rc = self.module_globals_rc.clone();

        self.module_globals = Some(module_globals_cell.clone());
        self.module_globals_rc = Some(module_globals_cell.clone());

        // Isolate exception state (same rationale as native_require).
        let saved_exception_handlers = std::mem::take(&mut self.exception_handlers);
        let saved_pending_exception = self.pending_exception.take();
        let result = self.execute(module);
        self.exception_handlers = saved_exception_handlers;
        self.pending_exception = saved_pending_exception;

        self.module_globals = saved_mg;
        self.module_globals_rc = saved_mg_rc;

        let module_globals = std::mem::replace(&mut self.globals, saved_globals.clone());
        let exec_exports = std::mem::replace(&mut self.module_exports, prev_exports);
        // Do NOT merge exec_exports back into module_exports. Each module's
        // exports are tracked separately via exec_store_module_export and
        // exec_reexport_all which update module_registry directly. Merging
        // would pollute the parent module's exports with nested module exports.
        //
        // Merge guard: a `import * as ns` binding creates a module-namespace
        // object in the global scope. The imported module may also export a
        // binding with the same name (e.g. `export const ns`), and the merge
        // below would otherwise clobber the namespace object with that export.
        // Never overwrite an existing module-namespace object.
        let is_existing_namespace =
            |globals: &FxHashMap<String, Value>, heap: &[HeapValue], k: &str| -> bool {
                if let Some(Value::Object(idx)) = globals.get(k) {
                    if let HeapValue::Object(o) = &heap[*idx] {
                        if o.properties.contains_key("__module_path") {
                            return true;
                        }
                    }
                }
                false
            };
        // Restore exported values
        for (k, v) in &exec_exports {
            if is_existing_namespace(&self.globals, &self.heap, k) {
                continue;
            }
            if let Some(mv) = module_globals.get(k) {
                self.set_global(k, mv.clone());
            } else {
                self.set_global(k, v.clone());
            }
        }
        // Also restore named imports that the module registered (via ImportNamed/ImportDefault/ImportAll)
        // These are globals that exist in module_globals but not in the original saved_globals
        for (k, v) in &module_globals {
            if !saved_globals.contains_key(k) {
                // Preserve functions and imports from the module.
                // Module-level variables (let/const/var) are NOT preserved here to avoid
                // polluting the global scope. They remain accessible via module_globals_rc
                // which is set before the module executes and used by LoadGlobal/StoreGlobal.
                if matches!(v, Value::Function(_) | Value::NativeFunction(_))
                    || exec_exports.contains_key(k)
                {
                    if is_existing_namespace(&self.globals, &self.heap, k) {
                        continue;
                    }
                    self.set_global(k, v.clone());
                }
            }
        }
        self.current_module = saved_module;
        result
    }

    pub(crate) fn load_and_run_module(&mut self, source: &str) -> Result<Option<String>> {
        if source.ends_with(".native") {
            // Try the full source as the module name first (e.g.
            // `import fs from "fs/promises"` registers the module
            // under `"fs/promises"`, not under the file-stem
            // `"promises"`). This lets users keep the Node.js
            // subpath import style without having to write
            // `import fs from "./fs-promises.native"`.
            let full_name = source.trim_end_matches(".native");
            if !self.native_loader.has_module(full_name) {
                super::native_loader::discover_module(full_name, &mut self.native_loader);
            }
            if self.native_loader.has_module(full_name) {
                let module_name = full_name;
                let exports =
                    self.native_loader
                        .load_module(module_name, &mut self.heap, &mut self.gc)?;
                let mut props = FxHashMap::default();
                for (name, val) in &exports {
                    props.insert(name.to_string(), val.clone());
                }
                self.module_registry.insert(module_name.to_string(), props);
                return Ok(Some(module_name.to_string()));
            }

            // Fall back to the file-stem (last path segment without
            // extension), used for traditional cdylib imports like
            // `import x from "./x.native"`.
            let module_name = super::native_loader::extract_module_name(source);
            if !self.native_loader.has_module(module_name) {
                // Resolve the path relative to the importing file's directory
                let resolved_path = if source.starts_with("./") || source.starts_with("../") {
                    // Relative path - resolve from current module's directory
                    let base = self.current_module_path.as_deref().unwrap_or(".");
                    let base_path = std::path::Path::new(base);
                    let parent = base_path.parent().unwrap_or(std::path::Path::new("."));
                    parent.join(source)
                } else if source.starts_with('/') {
                    // Absolute path
                    std::path::PathBuf::from(source)
                } else {
                    // Bare specifier like "my-module.native"
                    // Check node_modules first
                    let base = self.current_module_path.as_deref().unwrap_or(".");
                    let base_path = std::path::Path::new(base);
                    let parent = base_path.parent().unwrap_or(std::path::Path::new("."));

                    if let Some(resolved) = self.resolve_from_node_modules(source, parent, false) {
                        std::path::PathBuf::from(resolved)
                    } else {
                        // Fall back to ./dist/
                        let dist_dir = std::env::current_dir().unwrap_or_default().join("dist");
                        // Try with lib prefix and platform extension
                        let ext = if cfg!(target_os = "windows") {
                            "dll"
                        } else if cfg!(target_os = "macos") {
                            "dylib"
                        } else {
                            "so"
                        };
                        let with_ext = dist_dir.join(format!("{}.{}", module_name, ext));
                        if with_ext.exists() {
                            with_ext
                        } else {
                            let with_lib = dist_dir.join(format!("lib{}.{}", module_name, ext));
                            if with_lib.exists() {
                                with_lib
                            } else {
                                dist_dir.join(format!("{}.{}", module_name, ext))
                            }
                        }
                    }
                };

                // Try to load from the resolved path directly
                if resolved_path.exists() {
                    if let Some(props) = self.load_native_library(&resolved_path) {
                        self.module_registry.insert(module_name.to_string(), props);
                        return Ok(Some(module_name.to_string()));
                    }
                }

                // If the resolved path doesn't exist or failed to load,
                // try to find the library in the directory containing the resolved path
                if let Some(parent_dir) = resolved_path.parent() {
                    if let Some(lib_path) =
                        super::native_loader::find_library_in_dir(parent_dir, module_name)
                    {
                        if let Some(props) = self.load_native_library(&lib_path) {
                            self.module_registry.insert(module_name.to_string(), props);
                            return Ok(Some(module_name.to_string()));
                        }
                    }
                }

                // As a last resort, look in the project's ./dist/ directory.
                // This makes relative imports like `import x from "./x.native"`
                // work even when the script is in a temp directory, provided
                // the user has run `tails build` and the .so is in dist/.
                let dist_dir = std::env::current_dir().unwrap_or_default().join("dist");
                if let Some(lib_path) =
                    super::native_loader::find_library_in_dir(&dist_dir, module_name)
                {
                    if let Some(props) = self.load_native_library(&lib_path) {
                        self.module_registry.insert(module_name.to_string(), props);
                        return Ok(Some(module_name.to_string()));
                    }
                }

                // Fall back to static registration
                super::native_loader::discover_module(module_name, &mut self.native_loader);
            }
            if self.native_loader.has_module(module_name) {
                let exports =
                    self.native_loader
                        .load_module(module_name, &mut self.heap, &mut self.gc)?;
                // Set buffer_proto_idx when buffer module is loaded
                if module_name == wk::MOD_BUFFER {
                    if let Some(Value::Object(proto_idx)) = exports.get(wk::PROTOTYPE) {
                        self.buffer_proto_idx = Some(*proto_idx);
                    }
                }
                let mut props = FxHashMap::default();
                for (name, val) in &exports {
                    props.insert(name.to_string(), val.clone());
                }
                self.module_registry.insert(module_name.to_string(), props);
                return Ok(Some(module_name.to_string()));
            }
            return Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            )));
        }

        let module_path = match self.resolve_module_path(source) {
            Ok(p) => p,
            Err(_) => {
                // Bare native module name (e.g., "fs", "path", "process")
                let module_name = source;
                if !self.native_loader.has_module(module_name) {
                    // Try to load from ./dist/ first via the proper
                    // `load_native_library` path so the function pointers
                    // get registered in `dynamic_native_fns`.
                    let dist_dir = std::env::current_dir().unwrap_or_default().join("dist");
                    if let Some(lib_path) =
                        super::native_loader::find_library_in_dir(&dist_dir, module_name)
                    {
                        if let Some(props) = self.load_native_library(&lib_path) {
                            self.module_registry.insert(module_name.to_string(), props);
                            return Ok(Some(module_name.to_string()));
                        }
                    }
                    // Fall back to static registration
                    super::native_loader::discover_module(module_name, &mut self.native_loader);
                }
                if self.native_loader.has_module(module_name) {
                    let exports = self.native_loader.load_module(
                        module_name,
                        &mut self.heap,
                        &mut self.gc,
                    )?;
                    if module_name == wk::MOD_BUFFER {
                        if let Some(Value::Object(proto_idx)) = exports.get(wk::PROTOTYPE) {
                            self.buffer_proto_idx = Some(*proto_idx);
                        }
                    }
                    let mut props = FxHashMap::default();
                    for (name, val) in &exports {
                        props.insert(name.to_string(), val.clone());
                    }
                    self.module_registry.insert(module_name.to_string(), props);
                    return Ok(Some(module_name.to_string()));
                }
                return Err(Error::RuntimeError(format!(
                    "Cannot find module '{}'",
                    source
                )));
            }
        };
        if self.module_registry.contains_key(&module_path) {
            return Ok(Some(module_path));
        }
        let source_code = std::fs::read_to_string(&module_path)
            .map_err(|e| Error::RuntimeError(format!("Cannot read module '{}': {}", source, e)))?;
        // ESM `import` of a CommonJS module (e.g. `import x from '../index.js'`
        // inside an ESM file, where index.js is CJS) must run through the
        // `require` path so that `module.exports` is captured into the registry.
        // The ESM loader below only captures `export` statements and would
        // otherwise expose nothing, breaking `cjsModule.configure` style reads.
        if Self::is_cjs_source(&module_path, &source_code) {
            // Pass the original (relative) specifier so `require` resolves it
            // against the importing module's directory, rather than the already
            // joined path which `require`'s resolution mishandles.
            crate::runtime_env::native_fns::require_fns::native_require(
                self,
                &Value::Undefined,
                &[Value::from_string(source.to_string())],
            )?;
            return Ok(Some(module_path));
        }
        let mut tokens = crate::compiler::lexer::tokenize(&source_code)?;
        let ast = crate::compiler::parser::parse(&mut tokens)?;
        let compiled = crate::compiler::bytecode::generate(&ast)?;
        let prev_path = self.current_module_path.take();
        self.current_module_path = Some(module_path.clone());
        self.module_registry
            .insert(module_path.clone(), FxHashMap::default());
        let result = self.execute_module(&compiled);
        // Registry is already updated during execution via exec_store_module_export
        // and exec_reexport_all. No need to overwrite with module_exports here.
        self.current_module_path = prev_path;
        result?;
        Ok(Some(module_path))
    }

    pub(crate) fn resolve_module_path(&self, source: &str) -> Result<String> {
        self.resolve_module_path_with_context(source, false)
    }

    /// Like `resolve_module_path`, but lets the caller indicate a CJS `require`
    /// context so the package `exports` resolution can prefer the `require`
    /// condition over `import` (Node resolves `require()` against `require`).
    pub(crate) fn resolve_module_path_with_context(
        &self,
        source: &str,
        is_require: bool,
    ) -> Result<String> {
        let base = self.current_module_path.as_deref().unwrap_or(".");
        let base_path = std::path::Path::new(base);
        let parent = base_path.parent().unwrap_or(std::path::Path::new("."));

        if source.ends_with(".native") {
            return Ok(source.to_string());
        }

        let is_bare = !source.starts_with('.') && !source.starts_with('/');

        // For bare specifiers (e.g. "valibot"), skip local file checks and go straight to node_modules
        if !is_bare {
            // Include bare "." / ".." (common for package root re-exports)
            let resolved = if source == "."
                || source == ".."
                || source.starts_with("./")
                || source.starts_with("../")
            {
                parent.join(source)
            } else {
                std::path::PathBuf::from(source)
            };
            let normalized: std::path::PathBuf = resolved.components().collect();
            if normalized.exists() && normalized.is_file() {
                return Ok(normalized.to_string_lossy().to_string());
            }
            // Append extensions rather than Path::with_extension, so multi-dot
            // names like `./util.inspect` resolve to `util.inspect.js` (not `util.js`).
            for ext in &[".ts", ".js", ".cjs", ".mjs"] {
                let candidate =
                    std::path::PathBuf::from(format!("{}{}", normalized.to_string_lossy(), ext));
                if candidate.exists() {
                    return Ok(candidate.to_string_lossy().to_string());
                }
            }
            if normalized.is_dir() {
                for name in &["index.ts", "index.js", "index.cjs"] {
                    let idx = normalized.join(name);
                    if idx.exists() {
                        return Ok(idx.to_string_lossy().to_string());
                    }
                }
            }
        }

        // node_modules resolution for bare specifiers (no ./ or ../)
        if is_bare {
            if let Some(resolved) = self.resolve_from_node_modules(source, parent, is_require) {
                return Ok(resolved);
            }
        }

        Err(crate::errors::Error::RuntimeError(format!(
            "Module '{}' not found",
            source
        )))
    }

    /// Walk up the directory tree looking for node_modules/<pkg> and resolve its entry point
    fn resolve_from_node_modules(
        &self,
        specifier: &str,
        start_dir: &std::path::Path,
        is_require: bool,
    ) -> Option<String> {
        // Parse scoped package names: @scope/pkg/subpath -> (@scope/pkg, subpath)
        let (pkg_name, subpath) = if specifier.starts_with('@') {
            let mut parts = specifier.splitn(3, '/');
            let scope = parts.next()?;
            let name = parts.next()?;
            let sub = parts.next().unwrap_or("");
            (format!("{}/{}", scope, name), sub)
        } else {
            let mut parts = specifier.splitn(2, '/');
            let name = parts.next()?;
            let sub = parts.next().unwrap_or("");
            (name.to_string(), sub)
        };

        let mut current = Some(start_dir);
        while let Some(dir) = current {
            let pkg_dir = dir.join("node_modules").join(&pkg_name);
            if pkg_dir.is_dir() {
                return self.resolve_package_entry(&pkg_dir, subpath, is_require);
            }
            current = dir.parent();
        }
        None
    }

    /// Resolve a package's entry point from its package.json
    fn resolve_package_entry(
        &self,
        pkg_dir: &std::path::Path,
        subpath: &str,
        is_require: bool,
    ) -> Option<String> {
        // If there's a subpath, resolve that directly
        if !subpath.is_empty() {
            let sub = pkg_dir.join(subpath);
            return self.resolve_with_fallbacks(&sub);
        }

        // Read package.json
        let pkg_json_path = pkg_dir.join("package.json");
        let pkg_json = std::fs::read_to_string(&pkg_json_path).ok()?;
        let pkg: serde_json::Value = serde_json::from_str(&pkg_json).ok()?;

        // Priority: exports > module > main > index.js
        // Try exports["."]["import"] > exports["."]["default"] > exports["."]
        if let Some(exports) = pkg.get("exports") {
            if let Some(resolved) = self.resolve_exports_field(exports, pkg_dir, is_require) {
                return Some(resolved);
            }
        }

        // Try "module" field (ESM)
        if let Some(module) = pkg.get("module").and_then(|v| v.as_str()) {
            let path = pkg_dir.join(module);
            if let Some(r) = self.resolve_with_fallbacks(&path) {
                return Some(r);
            }
        }

        // Try "main" field
        if let Some(main) = pkg.get("main").and_then(|v| v.as_str()) {
            let path = pkg_dir.join(main);
            if let Some(r) = self.resolve_with_fallbacks(&path) {
                return Some(r);
            }
        }

        // Fallback: index.js
        self.resolve_with_fallbacks(&pkg_dir.join("index.js"))
    }

    /// Try the "exports" field with condition resolution
    fn resolve_exports_field(
        &self,
        exports: &serde_json::Value,
        pkg_dir: &std::path::Path,
        is_require: bool,
    ) -> Option<String> {
        match exports {
            // "exports": "./index.js"
            serde_json::Value::String(s) => {
                let path = pkg_dir.join(s);
                let normalized: std::path::PathBuf = path.components().collect();
                return self.resolve_with_fallbacks(&normalized);
            }
            // "exports": { ".": "...", "./sub": "..." }
            serde_json::Value::Object(map) => {
                // Direct condition map at the top level
                // (e.g. { "require": "./index.js", "import": "./esm/wrapper.js" })
                // — resolve using require/import ordering instead of only
                // looking for a "." sub-key.
                let is_top_level_condition = !map.contains_key(".")
                    && map.keys().any(|k| {
                        matches!(k.as_str(), "require" | "import" | "node" | "default" | "types")
                    });
                if is_top_level_condition {
                    return self.resolve_condition(
                        &serde_json::Value::Object(map.clone()),
                        pkg_dir,
                        is_require,
                    );
                }
                // Look for "." entry (the main entry)
                if let Some(dot_entry) = map.get(".") {
                    return self.resolve_condition(dot_entry, pkg_dir, is_require);
                }
                // If no "." key, maybe it's a condition map directly (e.g. {"import":"...", "default":"..."})
                // Try "import" then "default"
                if let Some(import_val) = map.get("import") {
                    if let Some(r) = self.resolve_condition(import_val, pkg_dir, is_require) {
                        return Some(r);
                    }
                }
                if let Some(default_val) = map.get("default") {
                    if let Some(r) = self.resolve_condition(default_val, pkg_dir, is_require) {
                        return Some(r);
                    }
                }
            }
            _ => {}
        }
        None
    }

    /// Resolve a single condition value (string or nested condition map)
    fn resolve_condition(
        &self,
        value: &serde_json::Value,
        pkg_dir: &std::path::Path,
        is_require: bool,
    ) -> Option<String> {
        match value {
            serde_json::Value::String(s) => {
                let path = pkg_dir.join(s);
                let normalized: std::path::PathBuf = path.components().collect();
                self.resolve_with_fallbacks(&normalized)
            }
            serde_json::Value::Object(map) => {
                // For a CJS `require()`, prefer the `require` condition; for ESM
                // `import`, prefer `import`. `default`/`node` are fallbacks.
                let conditions: &[&str] = if is_require {
                    &["require", "node", "import", "default"]
                } else {
                    &["import", "default", "require", "node"]
                };
                for condition in conditions {
                    if let Some(val) = map.get(*condition) {
                        if let Some(r) = self.resolve_condition(val, pkg_dir, is_require) {
                            return Some(r);
                        }
                    }
                }
                None
            }
            _ => None,
        }
    }

    /// Try resolving a path with .ts, .js, .cjs, /index.ts, /index.js fallbacks
    fn resolve_with_fallbacks(&self, path: &std::path::Path) -> Option<String> {
        if path.exists() && path.is_file() {
            return Some(path.to_string_lossy().to_string());
        }
        // Append extensions (do not strip multi-dot stems like `util.inspect`).
        for ext in &[".ts", ".js", ".mjs", ".cjs"] {
            let candidate = std::path::PathBuf::from(format!("{}{}", path.to_string_lossy(), ext));
            if candidate.exists() {
                return Some(candidate.to_string_lossy().to_string());
            }
        }
        if path.is_dir() {
            for name in &["index.ts", "index.js", "index.mjs", "index.cjs"] {
                let idx = path.join(name);
                if idx.exists() {
                    return Some(idx.to_string_lossy().to_string());
                }
            }
        }
        None
    }

    pub(crate) fn build_module_object_from_exports(
        &mut self,
        exports: &FxHashMap<String, Value>,
    ) -> Value {
        let heap_idx = self.heap.len();
        let mut props = FxHashMap::default();
        for (k, v) in exports {
            props.insert(k.clone(), v.clone());
        }
        // Tag as module namespace for live binding support.
        if let Some(path) = &self.current_module_path {
            props.insert(
                "__module_path".to_string(),
                Value::from_string(path.clone()),
            );
        }
        // Inherit Object.prototype so `exports.hasOwnProperty` etc. work
        // (Node module.exports is an ordinary object).
        self.heap.push(HeapValue::Object(JsObject {
            properties: PropertyStorage::Map(props),
            prototype: self.object_proto_idx,
            extensible: true,
        }));
        Value::Object(heap_idx)
    }

    /// Decide whether a `.js` file is CommonJS rather than ESM. A module is
    /// ESM when it contains `import`/`export` statements (or the package
    /// declares `"type": "module"`). Otherwise—when it relies on
    /// `module.exports`/`require`—it must be loaded through the CJS `require`
    /// path so its exports are captured into the registry.
    fn is_cjs_source(path: &str, source: &str) -> bool {
        // `.cjs` is always CommonJS; `.mjs` is always ESM.
        if path.ends_with(".cjs") {
            return true;
        }
        if path.ends_with(".mjs") {
            return false;
        }
        // Respect package.json `"type": "module"` for `.js` files.
        let mut dir = std::path::Path::new(path);
        for _ in 0..6 {
            dir = match dir.parent() {
                Some(d) => d,
                None => break,
            };
            let pkg = dir.join("package.json");
            if let Ok(text) = std::fs::read_to_string(&pkg) {
                if let Ok(json) = serde_json::from_str::<serde_json::Value>(&text) {
                    if let Some(t) = json.get("type").and_then(|v| v.as_str()) {
                        return t != "module";
                    }
                }
                break;
            }
        }
        // Heuristic: presence of top-level `import`/`export` statements marks ESM.
        // Scan only a prefix to stay cheap; this catches the common cases.
        let mut saw_export = false;
        let mut saw_import = false;
        for line in source.lines().take(200) {
            let trimmed = line.trim_start();
            if trimmed.starts_with("export ") || trimmed.starts_with("export{") {
                saw_export = true;
            }
            if trimmed.starts_with("import ") {
                saw_import = true;
            }
        }
        !(saw_export || saw_import)
    }

    pub(crate) fn build_error_promise(&mut self, message: String) -> Value {
        let reason_idx = self.heap.len();
        let props = props! {
            wk::MESSAGE => Value::from_string(message),
        };
        self.heap.push(HeapValue::Object(JsObject {
            properties: props,
            prototype: None,
            extensible: true,
        }));
        let promise_idx = self.heap.len();
        self.heap.push(HeapValue::Promise(
            crate::objects::js_promise::JsPromise::rejected(Value::Object(reason_idx)),
        ));
        Value::Promise(promise_idx)
    }

    pub(crate) fn build_module_promise(&mut self, exports: FxHashMap<String, Value>) -> Value {
        let module_obj = self.build_module_object_from_exports(&exports);
        let promise_idx = self.heap.len();
        self.heap.push(HeapValue::Promise(
            crate::objects::js_promise::JsPromise::fulfilled(module_obj),
        ));
        Value::Promise(promise_idx)
    }

    pub(crate) fn exec_import_module(&mut self, source: &str) -> Result<Option<Value>> {
        match self.load_and_run_module(source) {
            Ok(Some(module_path)) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                Ok(Some(self.build_module_object_from_exports(&exports)))
            }
            Ok(None) => Ok(Some(Value::Undefined)),
            Err(e) => Ok(Some(self.build_error_promise(e.message().to_string()))),
        }
    }

    pub(crate) fn exec_import_named(
        &mut self,
        source: &str,
        imported_name: &str,
        local_name: &str,
    ) -> Result<Value> {
        match self.load_and_run_module(source)? {
            Some(module_path) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                let val = exports
                    .get(imported_name)
                    .cloned()
                    .unwrap_or(Value::Undefined);
                self.set_global(local_name, val);
                Ok(Value::Undefined)
            }
            None => Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            ))),
        }
    }

    pub(crate) fn exec_import_default(&mut self, source: &str, local_name: &str) -> Result<Value> {
        match self.load_and_run_module(source)? {
            Some(module_path) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                let val = if let Some(v) = self.cjs_default_exports.get(&module_path) {
                    // CJS module that did `module.exports = fn` — ESM
                    // `import x from 'cjs'` resolves to that function directly
                    // (its properties like `.configure` are surfaced as named
                    // exports by native_require).
                    v.clone()
                } else if let Some(v) = exports.get("default") {
                    v.clone()
                } else if !exports.is_empty() {
                    self.build_module_object_from_exports(&exports)
                } else {
                    Value::Undefined
                };
                self.set_global(local_name, val);
                Ok(Value::Undefined)
            }
            None => Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            ))),
        }
    }

    pub(crate) fn exec_import_all(&mut self, source: &str, local_name: &str) -> Result<Value> {
        match self.load_and_run_module(source)? {
            Some(module_path) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                // Temporarily set current_module_path so the namespace object
                // is tagged with the correct module path for live binding.
                let prev_path = self.current_module_path.take();
                self.current_module_path = Some(module_path.clone());
                let module_obj = self.build_module_object_from_exports(&exports);
                self.current_module_path = prev_path;
                self.namespace_globals.insert(local_name.to_string());
                self.set_global(local_name, module_obj);
                Ok(Value::Undefined)
            }
            None => Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            ))),
        }
    }

    pub(crate) fn exec_native_import(&mut self, source: &str, local_name: &str) -> Result<Value> {
        match self.load_and_run_module(source)? {
            Some(module_path) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                let val = exports
                    .get("default")
                    .cloned()
                    .unwrap_or_else(|| self.build_module_object_from_exports(&exports));
                self.set_global(local_name, val);
                Ok(Value::Undefined)
            }
            None => Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            ))),
        }
    }

    pub(crate) fn exec_export_named(&mut self, names: &[String]) -> Result<()> {
        for name in names {
            if let Some(val) = self.globals.get(name) {
                self.module_exports.insert(name.clone(), val.clone());
                if let Some(path) = &self.current_module_path {
                    if let Some(exports) = self.module_registry.get_mut(path) {
                        exports.insert(name.clone(), val.clone());
                    }
                }
            }
        }
        Ok(())
    }

    pub(crate) fn exec_export_default(&mut self) -> Result<()> {
        let val = self.stack.last().cloned().unwrap_or(Value::Undefined);
        self.module_exports
            .insert("default".to_string(), val.clone());
        if let Some(path) = &self.current_module_path {
            if let Some(exports) = self.module_registry.get_mut(path) {
                exports.insert("default".to_string(), val);
            }
        }
        Ok(())
    }

    pub(crate) fn exec_store_module_export(&mut self, name: &str) -> Result<()> {
        if let Some(val) = self.globals.get(name) {
            self.module_exports.insert(name.to_string(), val.clone());
            if let Some(path) = &self.current_module_path {
                if let Some(exports) = self.module_registry.get_mut(path) {
                    exports.insert(name.to_string(), val.clone());
                }
            }
        }
        Ok(())
    }

    pub(crate) fn exec_reexport_all(&mut self, source: &str) -> Result<()> {
        match self.load_and_run_module(source)? {
            Some(module_path) => {
                let exports = self
                    .module_registry
                    .get(&module_path)
                    .cloned()
                    .unwrap_or_default();
                for (k, v) in &exports {
                    if k != "default" {
                        self.module_exports.insert(k.clone(), v.clone());
                        if let Some(path) = &self.current_module_path {
                            if let Some(current_exports) = self.module_registry.get_mut(path) {
                                current_exports.insert(k.clone(), v.clone());
                            }
                        }
                    }
                }
                Ok(())
            }
            None => Err(Error::RuntimeError(format!(
                "Cannot find module '{}'",
                source
            ))),
        }
    }
}
