#[allow(dead_code)]
pub struct DtsEntry {
    pub module_name: String,
    pub functions: Vec<FnDtsEntry>,
}

#[allow(dead_code)]
pub struct FnDtsEntry {
    pub name: String,
    pub signature: String,
}

#[allow(dead_code)]
pub fn generate_dts(entries: &[DtsEntry]) -> String {
    let mut output = String::new();

    for entry in entries {
        output.push_str("// Auto-generated by tails-native-macros\n");
        output.push_str("// Do not edit manually\n\n");

        for func in &entry.functions {
            output.push_str(&format!("{}\n", func.signature));
        }
    }

    output
}

#[allow(dead_code)]
pub fn collect_dts_metadata() -> proc_macro2::TokenStream {
    quote::quote! {
        pub fn __tails_generate_dts() -> String {
            let mut dts = String::new();
            dts.push_str("// Auto-generated by tails-native-macros\n");
            dts.push_str("// Do not edit manually\n\n");
            dts
        }
    }
}

#[allow(dead_code)]
pub fn expand_dts_collector(
    module_name: &str,
    fn_signatures: &[(String, String)],
) -> proc_macro2::TokenStream {
    let entries: Vec<proc_macro2::TokenStream> = fn_signatures
        .iter()
        .map(|(name, sig)| {
            quote::quote! {
                functions.push((#name.to_string(), #sig.to_string()));
            }
        })
        .collect();

    let collector_name =
        quote::format_ident!("__tails_dts_collector_{}", module_name.replace('-', "_"));

    quote::quote! {
        #[doc(hidden)]
        pub fn #collector_name() -> Vec<(String, String)> {
            let mut functions = Vec::new();
            #(#entries)*
            functions
        }
    }
}
